In [70]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

In [2]:
data = pd.read_csv('people_wiki.csv')

In [3]:
data.head()

,URI,name,text
0,<http://dbpedia.org/resource/Digby_Morrell>,Digby Morrell,digby morrell born 10 october 1979 is a former...
1,<http://dbpedia.org/resource/Alfred_J._Lewy>,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...
2,<http://dbpedia.org/resource/Harpdog_Brown>,Harpdog Brown,harpdog brown is a singer and harmonica player...
3,<http://dbpedia.org/resource/Franz_Rottensteiner>,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...
4,<http://dbpedia.org/resource/G-Enka>,G-Enka,henry krvits born 30 december 1974 in tallinn ...

In [5]:
data.shape

(1346, 3)

In [6]:
name1 = data[data['name'] == 'Franz Rottensteiner']

In [10]:
pd.set_option("display.max_colwidth", None)

In [14]:
pd.set_option("display.max_colwidth", None)

In [15]:
pd.reset_option("display.max_colwidth")

In [23]:
print(name1['text'])

3    franz rottensteiner born in waidmannsfeld lowe...
Name: text, dtype: object

In [ ]:
for t in name1['text']:
    print(t)

franz rottensteiner born in waidmannsfeld lower austria austria on 18 january 1942 is an austrian publisher and critic in the fields of science fiction and the fantasticrottensteiner studied journalism english and history at the university of vienna receiving his doctorate in 1969 he served about fifteen years as librarian and editor at the sterreichisches institut fr bauforschung in vienna in addition he produced a number of translations into german of leading sf authors including herbert w franke stanislaw lem philip k dick kobo abe cordwainer smith brian w aldiss and the strugatski brothersin 1973 his new york anthology view from another shore of european science fiction introduced a number of continental authors to the englishreading public some of the authors in the work are stanislaw lem josef nesvadba gerard klein and jeanpierre andrevonthe year 1975 saw the start of his series die phantastischen romane for seven years it republished works of both lesser and betterknown writers as well as new ones ending with a total of 28 volumes in the years 19791985 he brought out trnaslations of h g wellss works in an eighteen volumes seriesrottensteiner provoked some controversy with his negative assessment of american science fiction what matters is the highest achievements and there the us has yet to produce a figure comparable to hg wells olaf stapledon karel apek or stanisaw lem rottensteiner describedroger zelazny barry n malzberg and robert silverberg as producing travesties of fiction and stated asimov is a typical nonwriter and heinlein and andersonare just banal however rottensteiner praised philip k dick listing him as one of the greatest sf writers from 1980 through 1998 he was advisor for suhrkamp verlags phantastische bibliothek which brought out some three hundred books in all he has edited about fifty anthologies produced two illustrated books the science fiction book 1975 und the fantasy book 1978 as well as working on numerous reference works on science fiction his close association with and promotion of lem until 1995 was a factor in the recognition of the latter in the united statesrottensteiner has been the editor of quarber merkur the leading german language critical journal of science fiction since 1963 in 2004 on the occasion of the hundredth number of this journal he was awarded a special kurdlawitzpreis

In [35]:
from collections import Counter

In [36]:
text = name1['text'].astype(str)
name1['words_count'] = text.apply(lambda x: Counter(x.lower().split()))

/tmp/ipykernel_9679/3103118731.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  name1['words_count'] = text.apply(lambda x: Counter(x.lower().split()))

In [ ]:
for w in name1['words_count']:
    print(w)

Counter({'the': 22, 'of': 20, 'and': 13, 'in': 12, 'fiction': 7, 'as': 7, 'a': 7, 'science': 6, 'he': 6, 'his': 5, 'on': 4, 'lem': 4, 'rottensteiner': 3, 'is': 3, 'years': 3, 'number': 3, 'authors': 3, 'to': 3, 'some': 3, 'works': 3, 'with': 3, 'has': 3, 'was': 3, 'austria': 2, 'an': 2, 'at': 2, 'vienna': 2, 'about': 2, 'editor': 2, 'produced': 2, 'german': 2, 'leading': 2, 'sf': 2, 'w': 2, 'stanislaw': 2, 'philip': 2, 'k': 2, 'dick': 2, 'new': 2, 'from': 2, '1975': 2, 'for': 2, 'writers': 2, 'well': 2, 'volumes': 2, 'brought': 2, 'out': 2, 'books': 2, 'book': 2, 'journal': 2, 'franz': 1, 'born': 1, 'waidmannsfeld': 1, 'lower': 1, '18': 1, 'january': 1, '1942': 1, 'austrian': 1, 'publisher': 1, 'critic': 1, 'fields': 1, 'fantasticrottensteiner': 1, 'studied': 1, 'journalism': 1, 'english': 1, 'history': 1, 'university': 1, 'receiving': 1, 'doctorate': 1, '1969': 1, 'served': 1, 'fifteen': 1, 'librarian': 1, 'sterreichisches': 1, 'institut': 1, 'fr': 1, 'bauforschung': 1, 'addition': 1, 'translations': 1, 'into': 1, 'including': 1, 'herbert': 1, 'franke': 1, 'kobo': 1, 'abe': 1, 'cordwainer': 1, 'smith': 1, 'brian': 1, 'aldiss': 1, 'strugatski': 1, 'brothersin': 1, '1973': 1, 'york': 1, 'anthology': 1, 'view': 1, 'another': 1, 'shore': 1, 'european': 1, 'introduced': 1, 'continental': 1, 'englishreading': 1, 'public': 1, 'work': 1, 'are': 1, 'josef': 1, 'nesvadba': 1, 'gerard': 1, 'klein': 1, 'jeanpierre': 1, 'andrevonthe': 1, 'year': 1, 'saw': 1, 'start': 1, 'series': 1, 'die': 1, 'phantastischen': 1, 'romane': 1, 'seven': 1, 'it': 1, 'republished': 1, 'both': 1, 'lesser': 1, 'betterknown': 1, 'ones': 1, 'ending': 1, 'total': 1, '28': 1, '19791985': 1, 'trnaslations': 1, 'h': 1, 'g': 1, 'wellss': 1, 'eighteen': 1, 'seriesrottensteiner': 1, 'provoked': 1, 'controversy': 1, 'negative': 1, 'assessment': 1, 'american': 1, 'what': 1, 'matters': 1, 'highest': 1, 'achievements': 1, 'there': 1, 'us': 1, 'yet': 1, 'produce': 1, 'figure': 1, 'comparable': 1, 'hg': 1, 'wells': 1, 'olaf': 1, 'stapledon': 1, 'karel': 1, 'apek': 1, 'or': 1, 'stanisaw': 1, 'describedroger': 1, 'zelazny': 1, 'barry': 1, 'n': 1, 'malzberg': 1, 'robert': 1, 'silverberg': 1, 'producing': 1, 'travesties': 1, 'stated': 1, 'asimov': 1, 'typical': 1, 'nonwriter': 1, 'heinlein': 1, 'andersonare': 1, 'just': 1, 'banal': 1, 'however': 1, 'praised': 1, 'listing': 1, 'him': 1, 'one': 1, 'greatest': 1, '1980': 1, 'through': 1, '1998': 1, 'advisor': 1, 'suhrkamp': 1, 'verlags': 1, 'phantastische': 1, 'bibliothek': 1, 'which': 1, 'three': 1, 'hundred': 1, 'all': 1, 'edited': 1, 'fifty': 1, 'anthologies': 1, 'two': 1, 'illustrated': 1, 'und': 1, 'fantasy': 1, '1978': 1, 'working': 1, 'numerous': 1, 'reference': 1, 'close': 1, 'association': 1, 'promotion': 1, 'until': 1, '1995': 1, 'factor': 1, 'recognition': 1, 'latter': 1, 'united': 1, 'statesrottensteiner': 1, 'been': 1, 'quarber': 1, 'merkur': 1, 'language': 1, 'critical': 1, 'since': 1, '1963': 1, '2004': 1, 'occasion': 1, 'hundredth': 1, 'this': 1, 'awarded': 1, 'special': 1, 'kurdlawitzpreis': 1})

In [ ]:
text = data['text'].astype(str)

data['words_count'] = text.apply(lambda x: Counter(x.lower().split()))

In [59]:
data.head()

,URI,name,text,words_count
0,<http://dbpedia.org/resource/Digby_Morrell>,Digby Morrell,digby morrell born 10 october 1979 is a former...,"{'digby': 1, 'morrell': 5, 'born': 1, '10': 1,..."
1,<http://dbpedia.org/resource/Alfred_J._Lewy>,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...,"{'alfred': 1, 'j': 1, 'lewy': 3, 'aka': 1, 'sa..."
2,<http://dbpedia.org/resource/Harpdog_Brown>,Harpdog Brown,harpdog brown is a singer and harmonica player...,"{'harpdog': 2, 'brown': 2, 'is': 7, 'a': 7, 's..."
3,<http://dbpedia.org/resource/Franz_Rottensteiner>,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...,"{'franz': 1, 'rottensteiner': 3, 'born': 1, 'i..."
4,<http://dbpedia.org/resource/G-Enka>,G-Enka,henry krvits born 30 december 1974 in tallinn ...,"{'henry': 1, 'krvits': 1, 'born': 1, '30': 1, ..."

In [28]:
count_vector = CountVectorizer()

In [33]:
x = count_vector.fit_transform(name1['text'])

In [34]:
print(x)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 221 stored elements and shape (1, 221)>
  Coords	Values
  (0, 81)	1
  (0, 159)	3
  (0, 47)	1
  (0, 99)	12
  (0, 204)	1
  (0, 123)	1
  (0, 35)	2
  (0, 136)	4
  (0, 0)	1
  (0, 106)	1
  (0, 1)	1
  (0, 104)	3
  (0, 21)	2
  (0, 36)	1
  (0, 151)	1
  (0, 22)	13
  (0, 57)	1
  (0, 183)	22
  (0, 74)	1
  (0, 134)	20
  (0, 161)	6
  (0, 73)	7
  (0, 71)	1
  (0, 181)	1
  (0, 110)	1
  :	:
  (0, 52)	1
  (0, 33)	1
  (0, 148)	1
  (0, 198)	1
  (0, 9)	1
  (0, 70)	1
  (0, 154)	1
  (0, 117)	1
  (0, 196)	1
  (0, 178)	1
  (0, 42)	1
  (0, 152)	1
  (0, 126)	1
  (0, 116)	1
  (0, 58)	1
  (0, 109)	2
  (0, 169)	1
  (0, 2)	1
  (0, 11)	1
  (0, 133)	1
  (0, 97)	1
  (0, 185)	1
  (0, 38)	1
  (0, 172)	1
  (0, 115)	1

In [40]:
count_vector.get_feature_names_out()

array(['18', '1942', '1963', '1969', '1973', '1975', '1978', '19791985',
       '1980', '1995', '1998', '2004', '28', 'abe', 'about',
       'achievements', 'addition', 'advisor', 'aldiss', 'all', 'american',
       'an', 'and', 'andersonare', 'andrevonthe', 'another',
       'anthologies', 'anthology', 'apek', 'are', 'as', 'asimov',
       'assessment', 'association', 'at', 'austria', 'austrian',
       'authors', 'awarded', 'banal', 'barry', 'bauforschung', 'been',
       'betterknown', 'bibliothek', 'book', 'books', 'born', 'both',
       'brian', 'brothersin', 'brought', 'close', 'comparable',
       'continental', 'controversy', 'cordwainer', 'critic', 'critical',
       'describedroger', 'dick', 'die', 'doctorate', 'edited', 'editor',
       'eighteen', 'ending', 'english', 'englishreading', 'european',
       'factor', 'fantasticrottensteiner', 'fantasy', 'fiction', 'fields',
       'fifteen', 'fifty', 'figure', 'for', 'fr', 'franke', 'franz',
       'from', 'gerard', 'german', 'greatest', 'has', 'he', 'heinlein',
       'herbert', 'hg', 'highest', 'him', 'his', 'history', 'however',
       'hundred', 'hundredth', 'illustrated', 'in', 'including',
       'institut', 'into', 'introduced', 'is', 'it', 'january',
       'jeanpierre', 'josef', 'journal', 'journalism', 'just', 'karel',
       'klein', 'kobo', 'kurdlawitzpreis', 'language', 'latter',
       'leading', 'lem', 'lesser', 'librarian', 'listing', 'lower',
       'malzberg', 'matters', 'merkur', 'negative', 'nesvadba', 'new',
       'nonwriter', 'number', 'numerous', 'occasion', 'of', 'olaf', 'on',
       'one', 'ones', 'or', 'out', 'phantastische', 'phantastischen',
       'philip', 'praised', 'produce', 'produced', 'producing',
       'promotion', 'provoked', 'public', 'publisher', 'quarber',
       'receiving', 'recognition', 'reference', 'republished', 'robert',
       'romane', 'rottensteiner', 'saw', 'science', 'series',
       'seriesrottensteiner', 'served', 'seven', 'sf', 'shore',
       'silverberg', 'since', 'smith', 'some', 'special', 'stanisaw',
       'stanislaw', 'stapledon', 'start', 'stated', 'statesrottensteiner',
       'sterreichisches', 'strugatski', 'studied', 'suhrkamp', 'the',
       'there', 'this', 'three', 'through', 'to', 'total', 'translations',
       'travesties', 'trnaslations', 'two', 'typical', 'und', 'united',
       'university', 'until', 'us', 'verlags', 'vienna', 'view',
       'volumes', 'waidmannsfeld', 'was', 'well', 'wells', 'wellss',
       'what', 'which', 'with', 'work', 'working', 'works', 'writers',
       'year', 'years', 'yet', 'york', 'zelazny'], dtype=object)

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [63]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['text'])

In [72]:
knn = NearestNeighbors(n_neighbors=10, metric='cosine')
knn.fit(tfidf_matrix)

NearestNeighbors(metric='cosine', n_neighbors=10)

In [73]:
def retervial(query):
    query_vec = tfidf.transform([query])
    distance, indices = knn.kneighbors(query_vec, n_neighbors=10)
    print(f'finding the name for {query}')
    for i, idx in enumerate(indices):
        print(f'{i}, {data['name'].iloc[idx]}')

In [75]:
data.head()

,URI,name,text,words_count,tfidf
0,<http://dbpedia.org/resource/Digby_Morrell>,Digby Morrell,digby morrell born 10 october 1979 is a former...,"{'digby': 1, 'morrell': 5, 'born': 1, '10': 1,...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,<http://dbpedia.org/resource/Alfred_J._Lewy>,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...,"{'alfred': 1, 'j': 1, 'lewy': 3, 'aka': 1, 'sa...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,<http://dbpedia.org/resource/Harpdog_Brown>,Harpdog Brown,harpdog brown is a singer and harmonica player...,"{'harpdog': 2, 'brown': 2, 'is': 7, 'a': 7, 's...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,<http://dbpedia.org/resource/Franz_Rottensteiner>,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...,"{'franz': 1, 'rottensteiner': 3, 'born': 1, 'i...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,<http://dbpedia.org/resource/G-Enka>,G-Enka,henry krvits born 30 december 1974 in tallinn ...,"{'henry': 1, 'krvits': 1, 'born': 1, '30': 1, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

In [74]:
retervial('digby morrell born 10 october 1979 is a former')

finding the name for digby morrell born 10 october 1979 is a former
0, 0                             Digby Morrell
371                          Ruben Zackhras
422                           Lene Espersen
578                  Luis Medina (baseball)
903                           Mark Kirchner
159                         Yevgeniy Chazov
28                             Leon Hapgood
732      Kevin Rose (footballer, born 1960)
152                Roger James (footballer)
200    Mick O'Brien (footballer, born 1979)
Name: name, dtype: object

In [78]:
retervial('alfred j lewy aka sandy lewy graduated from')

finding the name for alfred j lewy aka sandy lewy graduated from
0, 1                  Alfred J. Lewy
1002                 Gordon Cyrus
362       Sam Stephenson (writer)
97              David Shaughnessy
737              Jarrod Bernstein
753                    Gina Haley
90      Patricia Crowther (caver)
1186                    Ben Turok
1187              Jaclyn A. Smith
1190                   Julie Gold
Name: name, dtype: object

In [77]:
data.head()

,URI,name,text,words_count
0,<http://dbpedia.org/resource/Digby_Morrell>,Digby Morrell,digby morrell born 10 october 1979 is a former...,"{'digby': 1, 'morrell': 5, 'born': 1, '10': 1,..."
1,<http://dbpedia.org/resource/Alfred_J._Lewy>,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...,"{'alfred': 1, 'j': 1, 'lewy': 3, 'aka': 1, 'sa..."
2,<http://dbpedia.org/resource/Harpdog_Brown>,Harpdog Brown,harpdog brown is a singer and harmonica player...,"{'harpdog': 2, 'brown': 2, 'is': 7, 'a': 7, 's..."
3,<http://dbpedia.org/resource/Franz_Rottensteiner>,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...,"{'franz': 1, 'rottensteiner': 3, 'born': 1, 'i..."
4,<http://dbpedia.org/resource/G-Enka>,G-Enka,henry krvits born 30 december 1974 in tallinn ...,"{'henry': 1, 'krvits': 1, 'born': 1, '30': 1, ..."

In [76]:
data = data.drop('tfidf', axis=1)